package com.crowdfunding.mapper;

import com.crowdfunding.pojo.CrowdLetter;
import com.crowdfunding.pojo.CrowdLetterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrowdLetterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(CrowdLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(CrowdLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(CrowdLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(CrowdLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<CrowdLetter> selectByExample(CrowdLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    CrowdLetter selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrowdLetter record, @Param("example") CrowdLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") CrowdLetter record, @Param("example") CrowdLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(CrowdLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_letter
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(CrowdLetter record);
}