package com.crowdfunding.mapper;

import com.crowdfunding.pojo.CrowdBankcard;
import com.crowdfunding.pojo.CrowdBankcardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrowdBankcardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(CrowdBankcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(CrowdBankcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(CrowdBankcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(CrowdBankcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<CrowdBankcard> selectByExample(CrowdBankcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    CrowdBankcard selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrowdBankcard record, @Param("example") CrowdBankcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") CrowdBankcard record, @Param("example") CrowdBankcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(CrowdBankcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_bankcard
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(CrowdBankcard record);
}