package com.crowdfunding.mapper;

import com.crowdfunding.pojo.ProjPrice;
import com.crowdfunding.pojo.ProjPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(ProjPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(ProjPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(ProjPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(ProjPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<ProjPrice> selectByExample(ProjPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    ProjPrice selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProjPrice record, @Param("example") ProjPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") ProjPrice record, @Param("example") ProjPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(ProjPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(ProjPrice record);
}