package com.crowdfunding.mapper;

import com.crowdfunding.pojo.ProjTenancy;
import com.crowdfunding.pojo.ProjTenancyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjTenancyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(ProjTenancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(ProjTenancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(ProjTenancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(ProjTenancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<ProjTenancy> selectByExample(ProjTenancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    ProjTenancy selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProjTenancy record, @Param("example") ProjTenancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") ProjTenancy record, @Param("example") ProjTenancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(ProjTenancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(ProjTenancy record);
}