package com.crowdfunding.mapper;

import com.crowdfunding.pojo.RegistrationUser;
import com.crowdfunding.pojo.RegistrationUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegistrationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(RegistrationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(RegistrationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(RegistrationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(RegistrationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<RegistrationUser> selectByExampleWithBLOBs(RegistrationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<RegistrationUser> selectByExample(RegistrationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    RegistrationUser selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") RegistrationUser record, @Param("example") RegistrationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") RegistrationUser record, @Param("example") RegistrationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") RegistrationUser record, @Param("example") RegistrationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(RegistrationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(RegistrationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_user
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(RegistrationUser record);
}