package com.crowdfunding.pojo;

public class ActivityReservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.RESERVATION_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String reservationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.IS_RESERVATION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String isReservation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.RESERVATION_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String reservationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.ACTIVITY_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String activityUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_reservation.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.UUID
     *
     * @return the value of activity_reservation.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.UUID
     *
     * @param uuid the value for activity_reservation.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.USER_UUID
     *
     * @return the value of activity_reservation.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.USER_UUID
     *
     * @param userUuid the value for activity_reservation.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.RESERVATION_DATE
     *
     * @return the value of activity_reservation.RESERVATION_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getReservationDate() {
        return reservationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.RESERVATION_DATE
     *
     * @param reservationDate the value for activity_reservation.RESERVATION_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setReservationDate(String reservationDate) {
        this.reservationDate = reservationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.IS_RESERVATION
     *
     * @return the value of activity_reservation.IS_RESERVATION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getIsReservation() {
        return isReservation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.IS_RESERVATION
     *
     * @param isReservation the value for activity_reservation.IS_RESERVATION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setIsReservation(String isReservation) {
        this.isReservation = isReservation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.RESERVATION_TYPE
     *
     * @return the value of activity_reservation.RESERVATION_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getReservationType() {
        return reservationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.RESERVATION_TYPE
     *
     * @param reservationType the value for activity_reservation.RESERVATION_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setReservationType(String reservationType) {
        this.reservationType = reservationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.ACTIVITY_UUID
     *
     * @return the value of activity_reservation.ACTIVITY_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getActivityUuid() {
        return activityUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.ACTIVITY_UUID
     *
     * @param activityUuid the value for activity_reservation.ACTIVITY_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setActivityUuid(String activityUuid) {
        this.activityUuid = activityUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.CANCEL
     *
     * @return the value of activity_reservation.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.CANCEL
     *
     * @param cancel the value for activity_reservation.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCancel(String cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_reservation.COMMENTS
     *
     * @return the value of activity_reservation.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_reservation.COMMENTS
     *
     * @param comments the value for activity_reservation.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}