package com.crowdfunding.pojo;

public class CrowdBankcard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.AMOUNT_ID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String amountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.AMOUNT_NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String amountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.USERNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.STATUS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String accountUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.CREATEDATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.TRXID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String trxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_bankcard.USRCUSTID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String usrcustid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.UUID
     *
     * @return the value of crowd_bankcard.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.UUID
     *
     * @param uuid the value for crowd_bankcard.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.USER_UUID
     *
     * @return the value of crowd_bankcard.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.USER_UUID
     *
     * @param userUuid the value for crowd_bankcard.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.AMOUNT_ID
     *
     * @return the value of crowd_bankcard.AMOUNT_ID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getAmountId() {
        return amountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.AMOUNT_ID
     *
     * @param amountId the value for crowd_bankcard.AMOUNT_ID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setAmountId(String amountId) {
        this.amountId = amountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.AMOUNT_NAME
     *
     * @return the value of crowd_bankcard.AMOUNT_NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getAmountName() {
        return amountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.AMOUNT_NAME
     *
     * @param amountName the value for crowd_bankcard.AMOUNT_NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setAmountName(String amountName) {
        this.amountName = amountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.USERNAME
     *
     * @return the value of crowd_bankcard.USERNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.USERNAME
     *
     * @param username the value for crowd_bankcard.USERNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.STATUS
     *
     * @return the value of crowd_bankcard.STATUS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.STATUS
     *
     * @param status the value for crowd_bankcard.STATUS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.COMMENTS
     *
     * @return the value of crowd_bankcard.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.COMMENTS
     *
     * @param comments the value for crowd_bankcard.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.CANCEL
     *
     * @return the value of crowd_bankcard.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.CANCEL
     *
     * @param cancel the value for crowd_bankcard.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCancel(String cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.ACCOUNT_UUID
     *
     * @return the value of crowd_bankcard.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getAccountUuid() {
        return accountUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.ACCOUNT_UUID
     *
     * @param accountUuid the value for crowd_bankcard.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setAccountUuid(String accountUuid) {
        this.accountUuid = accountUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.CREATEDATE
     *
     * @return the value of crowd_bankcard.CREATEDATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.CREATEDATE
     *
     * @param createdate the value for crowd_bankcard.CREATEDATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.TRXID
     *
     * @return the value of crowd_bankcard.TRXID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getTrxid() {
        return trxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.TRXID
     *
     * @param trxid the value for crowd_bankcard.TRXID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setTrxid(String trxid) {
        this.trxid = trxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_bankcard.USRCUSTID
     *
     * @return the value of crowd_bankcard.USRCUSTID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUsrcustid() {
        return usrcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_bankcard.USRCUSTID
     *
     * @param usrcustid the value for crowd_bankcard.USRCUSTID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUsrcustid(String usrcustid) {
        this.usrcustid = usrcustid;
    }
}