package com.crowdfunding.pojo;

public class CrowdBusniess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String accountUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.BUSINESS_NUMBER
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String businessNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.BUSINESS_DATETIME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String businessDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.BUSINESS_AMOUNT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String businessAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String projUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.CROWD_COUNT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String crowdCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.OLDACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String oldaccountUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.MARKET_PRICE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.BUSINESS_AMOUNT_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String businessAmountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.BUSINESS_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_busniess.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String userUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.UUID
     *
     * @return the value of crowd_busniess.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.UUID
     *
     * @param uuid the value for crowd_busniess.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.ACCOUNT_UUID
     *
     * @return the value of crowd_busniess.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getAccountUuid() {
        return accountUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.ACCOUNT_UUID
     *
     * @param accountUuid the value for crowd_busniess.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setAccountUuid(String accountUuid) {
        this.accountUuid = accountUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.BUSINESS_NUMBER
     *
     * @return the value of crowd_busniess.BUSINESS_NUMBER
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBusinessNumber() {
        return businessNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.BUSINESS_NUMBER
     *
     * @param businessNumber the value for crowd_busniess.BUSINESS_NUMBER
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBusinessNumber(String businessNumber) {
        this.businessNumber = businessNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.BUSINESS_DATETIME
     *
     * @return the value of crowd_busniess.BUSINESS_DATETIME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBusinessDatetime() {
        return businessDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.BUSINESS_DATETIME
     *
     * @param businessDatetime the value for crowd_busniess.BUSINESS_DATETIME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBusinessDatetime(String businessDatetime) {
        this.businessDatetime = businessDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.BUSINESS_AMOUNT
     *
     * @return the value of crowd_busniess.BUSINESS_AMOUNT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBusinessAmount() {
        return businessAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.BUSINESS_AMOUNT
     *
     * @param businessAmount the value for crowd_busniess.BUSINESS_AMOUNT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBusinessAmount(String businessAmount) {
        this.businessAmount = businessAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.PROJ_UUID
     *
     * @return the value of crowd_busniess.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getProjUuid() {
        return projUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.PROJ_UUID
     *
     * @param projUuid the value for crowd_busniess.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setProjUuid(String projUuid) {
        this.projUuid = projUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.CROWD_COUNT
     *
     * @return the value of crowd_busniess.CROWD_COUNT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCrowdCount() {
        return crowdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.CROWD_COUNT
     *
     * @param crowdCount the value for crowd_busniess.CROWD_COUNT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCrowdCount(String crowdCount) {
        this.crowdCount = crowdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.TYPE
     *
     * @return the value of crowd_busniess.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.TYPE
     *
     * @param type the value for crowd_busniess.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.OLDACCOUNT_UUID
     *
     * @return the value of crowd_busniess.OLDACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getOldaccountUuid() {
        return oldaccountUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.OLDACCOUNT_UUID
     *
     * @param oldaccountUuid the value for crowd_busniess.OLDACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setOldaccountUuid(String oldaccountUuid) {
        this.oldaccountUuid = oldaccountUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.CANCEL
     *
     * @return the value of crowd_busniess.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.CANCEL
     *
     * @param cancel the value for crowd_busniess.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCancel(String cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.MARKET_PRICE
     *
     * @return the value of crowd_busniess.MARKET_PRICE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.MARKET_PRICE
     *
     * @param marketPrice the value for crowd_busniess.MARKET_PRICE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setMarketPrice(String marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.BUSINESS_AMOUNT_TYPE
     *
     * @return the value of crowd_busniess.BUSINESS_AMOUNT_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBusinessAmountType() {
        return businessAmountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.BUSINESS_AMOUNT_TYPE
     *
     * @param businessAmountType the value for crowd_busniess.BUSINESS_AMOUNT_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBusinessAmountType(String businessAmountType) {
        this.businessAmountType = businessAmountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.BUSINESS_TYPE
     *
     * @return the value of crowd_busniess.BUSINESS_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.BUSINESS_TYPE
     *
     * @param businessType the value for crowd_busniess.BUSINESS_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.COMMENTS
     *
     * @return the value of crowd_busniess.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.COMMENTS
     *
     * @param comments the value for crowd_busniess.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_busniess.USER_UUID
     *
     * @return the value of crowd_busniess.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_busniess.USER_UUID
     *
     * @param userUuid the value for crowd_busniess.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }
}