package com.crowdfunding.pojo;

import java.util.ArrayList;
import java.util.List;

public class CrowdTransJournalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public CrowdTransJournalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andJournalIsNull() {
            addCriterion("journal is null");
            return (Criteria) this;
        }

        public Criteria andJournalIsNotNull() {
            addCriterion("journal is not null");
            return (Criteria) this;
        }

        public Criteria andJournalEqualTo(String value) {
            addCriterion("journal =", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotEqualTo(String value) {
            addCriterion("journal <>", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThan(String value) {
            addCriterion("journal >", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThanOrEqualTo(String value) {
            addCriterion("journal >=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThan(String value) {
            addCriterion("journal <", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThanOrEqualTo(String value) {
            addCriterion("journal <=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLike(String value) {
            addCriterion("journal like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotLike(String value) {
            addCriterion("journal not like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalIn(List<String> values) {
            addCriterion("journal in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotIn(List<String> values) {
            addCriterion("journal not in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalBetween(String value1, String value2) {
            addCriterion("journal between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotBetween(String value1, String value2) {
            addCriterion("journal not between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andTransCodeIsNull() {
            addCriterion("trans_code is null");
            return (Criteria) this;
        }

        public Criteria andTransCodeIsNotNull() {
            addCriterion("trans_code is not null");
            return (Criteria) this;
        }

        public Criteria andTransCodeEqualTo(String value) {
            addCriterion("trans_code =", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotEqualTo(String value) {
            addCriterion("trans_code <>", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeGreaterThan(String value) {
            addCriterion("trans_code >", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeGreaterThanOrEqualTo(String value) {
            addCriterion("trans_code >=", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLessThan(String value) {
            addCriterion("trans_code <", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLessThanOrEqualTo(String value) {
            addCriterion("trans_code <=", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeLike(String value) {
            addCriterion("trans_code like", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotLike(String value) {
            addCriterion("trans_code not like", value, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeIn(List<String> values) {
            addCriterion("trans_code in", values, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotIn(List<String> values) {
            addCriterion("trans_code not in", values, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeBetween(String value1, String value2) {
            addCriterion("trans_code between", value1, value2, "transCode");
            return (Criteria) this;
        }

        public Criteria andTransCodeNotBetween(String value1, String value2) {
            addCriterion("trans_code not between", value1, value2, "transCode");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("user_no is null");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("user_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserNoEqualTo(String value) {
            addCriterion("user_no =", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotEqualTo(String value) {
            addCriterion("user_no <>", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThan(String value) {
            addCriterion("user_no >", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(String value) {
            addCriterion("user_no >=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThan(String value) {
            addCriterion("user_no <", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThanOrEqualTo(String value) {
            addCriterion("user_no <=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLike(String value) {
            addCriterion("user_no like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotLike(String value) {
            addCriterion("user_no not like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIn(List<String> values) {
            addCriterion("user_no in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotIn(List<String> values) {
            addCriterion("user_no not in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoBetween(String value1, String value2) {
            addCriterion("user_no between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotBetween(String value1, String value2) {
            addCriterion("user_no not between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoIsNull() {
            addCriterion("related_user_no is null");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoIsNotNull() {
            addCriterion("related_user_no is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoEqualTo(String value) {
            addCriterion("related_user_no =", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoNotEqualTo(String value) {
            addCriterion("related_user_no <>", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoGreaterThan(String value) {
            addCriterion("related_user_no >", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoGreaterThanOrEqualTo(String value) {
            addCriterion("related_user_no >=", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoLessThan(String value) {
            addCriterion("related_user_no <", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoLessThanOrEqualTo(String value) {
            addCriterion("related_user_no <=", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoLike(String value) {
            addCriterion("related_user_no like", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoNotLike(String value) {
            addCriterion("related_user_no not like", value, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoIn(List<String> values) {
            addCriterion("related_user_no in", values, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoNotIn(List<String> values) {
            addCriterion("related_user_no not in", values, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoBetween(String value1, String value2) {
            addCriterion("related_user_no between", value1, value2, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andRelatedUserNoNotBetween(String value1, String value2) {
            addCriterion("related_user_no not between", value1, value2, "relatedUserNo");
            return (Criteria) this;
        }

        public Criteria andTransAmtIsNull() {
            addCriterion("trans_amt is null");
            return (Criteria) this;
        }

        public Criteria andTransAmtIsNotNull() {
            addCriterion("trans_amt is not null");
            return (Criteria) this;
        }

        public Criteria andTransAmtEqualTo(String value) {
            addCriterion("trans_amt =", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtNotEqualTo(String value) {
            addCriterion("trans_amt <>", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtGreaterThan(String value) {
            addCriterion("trans_amt >", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtGreaterThanOrEqualTo(String value) {
            addCriterion("trans_amt >=", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtLessThan(String value) {
            addCriterion("trans_amt <", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtLessThanOrEqualTo(String value) {
            addCriterion("trans_amt <=", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtLike(String value) {
            addCriterion("trans_amt like", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtNotLike(String value) {
            addCriterion("trans_amt not like", value, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtIn(List<String> values) {
            addCriterion("trans_amt in", values, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtNotIn(List<String> values) {
            addCriterion("trans_amt not in", values, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtBetween(String value1, String value2) {
            addCriterion("trans_amt between", value1, value2, "transAmt");
            return (Criteria) this;
        }

        public Criteria andTransAmtNotBetween(String value1, String value2) {
            addCriterion("trans_amt not between", value1, value2, "transAmt");
            return (Criteria) this;
        }

        public Criteria andDivideInfoIsNull() {
            addCriterion("divide_info is null");
            return (Criteria) this;
        }

        public Criteria andDivideInfoIsNotNull() {
            addCriterion("divide_info is not null");
            return (Criteria) this;
        }

        public Criteria andDivideInfoEqualTo(String value) {
            addCriterion("divide_info =", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoNotEqualTo(String value) {
            addCriterion("divide_info <>", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoGreaterThan(String value) {
            addCriterion("divide_info >", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoGreaterThanOrEqualTo(String value) {
            addCriterion("divide_info >=", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoLessThan(String value) {
            addCriterion("divide_info <", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoLessThanOrEqualTo(String value) {
            addCriterion("divide_info <=", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoLike(String value) {
            addCriterion("divide_info like", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoNotLike(String value) {
            addCriterion("divide_info not like", value, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoIn(List<String> values) {
            addCriterion("divide_info in", values, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoNotIn(List<String> values) {
            addCriterion("divide_info not in", values, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoBetween(String value1, String value2) {
            addCriterion("divide_info between", value1, value2, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andDivideInfoNotBetween(String value1, String value2) {
            addCriterion("divide_info not between", value1, value2, "divideInfo");
            return (Criteria) this;
        }

        public Criteria andErrMsgIsNull() {
            addCriterion("err_msg is null");
            return (Criteria) this;
        }

        public Criteria andErrMsgIsNotNull() {
            addCriterion("err_msg is not null");
            return (Criteria) this;
        }

        public Criteria andErrMsgEqualTo(String value) {
            addCriterion("err_msg =", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotEqualTo(String value) {
            addCriterion("err_msg <>", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgGreaterThan(String value) {
            addCriterion("err_msg >", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgGreaterThanOrEqualTo(String value) {
            addCriterion("err_msg >=", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgLessThan(String value) {
            addCriterion("err_msg <", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgLessThanOrEqualTo(String value) {
            addCriterion("err_msg <=", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgLike(String value) {
            addCriterion("err_msg like", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotLike(String value) {
            addCriterion("err_msg not like", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgIn(List<String> values) {
            addCriterion("err_msg in", values, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotIn(List<String> values) {
            addCriterion("err_msg not in", values, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgBetween(String value1, String value2) {
            addCriterion("err_msg between", value1, value2, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotBetween(String value1, String value2) {
            addCriterion("err_msg not between", value1, value2, "errMsg");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeIsNull() {
            addCriterion("trans_datetime is null");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeIsNotNull() {
            addCriterion("trans_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeEqualTo(String value) {
            addCriterion("trans_datetime =", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeNotEqualTo(String value) {
            addCriterion("trans_datetime <>", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeGreaterThan(String value) {
            addCriterion("trans_datetime >", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("trans_datetime >=", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeLessThan(String value) {
            addCriterion("trans_datetime <", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeLessThanOrEqualTo(String value) {
            addCriterion("trans_datetime <=", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeLike(String value) {
            addCriterion("trans_datetime like", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeNotLike(String value) {
            addCriterion("trans_datetime not like", value, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeIn(List<String> values) {
            addCriterion("trans_datetime in", values, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeNotIn(List<String> values) {
            addCriterion("trans_datetime not in", values, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeBetween(String value1, String value2) {
            addCriterion("trans_datetime between", value1, value2, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andTransDatetimeNotBetween(String value1, String value2) {
            addCriterion("trans_datetime not between", value1, value2, "transDatetime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andMerPrivIsNull() {
            addCriterion("mer_priv is null");
            return (Criteria) this;
        }

        public Criteria andMerPrivIsNotNull() {
            addCriterion("mer_priv is not null");
            return (Criteria) this;
        }

        public Criteria andMerPrivEqualTo(String value) {
            addCriterion("mer_priv =", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivNotEqualTo(String value) {
            addCriterion("mer_priv <>", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivGreaterThan(String value) {
            addCriterion("mer_priv >", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivGreaterThanOrEqualTo(String value) {
            addCriterion("mer_priv >=", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivLessThan(String value) {
            addCriterion("mer_priv <", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivLessThanOrEqualTo(String value) {
            addCriterion("mer_priv <=", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivLike(String value) {
            addCriterion("mer_priv like", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivNotLike(String value) {
            addCriterion("mer_priv not like", value, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivIn(List<String> values) {
            addCriterion("mer_priv in", values, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivNotIn(List<String> values) {
            addCriterion("mer_priv not in", values, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivBetween(String value1, String value2) {
            addCriterion("mer_priv between", value1, value2, "merPriv");
            return (Criteria) this;
        }

        public Criteria andMerPrivNotBetween(String value1, String value2) {
            addCriterion("mer_priv not between", value1, value2, "merPriv");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNull() {
            addCriterion("account_no is null");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNotNull() {
            addCriterion("account_no is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNoEqualTo(String value) {
            addCriterion("account_no =", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotEqualTo(String value) {
            addCriterion("account_no <>", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThan(String value) {
            addCriterion("account_no >", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThanOrEqualTo(String value) {
            addCriterion("account_no >=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThan(String value) {
            addCriterion("account_no <", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThanOrEqualTo(String value) {
            addCriterion("account_no <=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLike(String value) {
            addCriterion("account_no like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotLike(String value) {
            addCriterion("account_no not like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoIn(List<String> values) {
            addCriterion("account_no in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotIn(List<String> values) {
            addCriterion("account_no not in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoBetween(String value1, String value2) {
            addCriterion("account_no between", value1, value2, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotBetween(String value1, String value2) {
            addCriterion("account_no not between", value1, value2, "accountNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}