package com.crowdfunding.pojo;

import java.util.ArrayList;
import java.util.List;

public class ProjPriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public ProjPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidIsNull() {
            addCriterion("PROJ_UUID is null");
            return (Criteria) this;
        }

        public Criteria andProjUuidIsNotNull() {
            addCriterion("PROJ_UUID is not null");
            return (Criteria) this;
        }

        public Criteria andProjUuidEqualTo(String value) {
            addCriterion("PROJ_UUID =", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotEqualTo(String value) {
            addCriterion("PROJ_UUID <>", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidGreaterThan(String value) {
            addCriterion("PROJ_UUID >", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidGreaterThanOrEqualTo(String value) {
            addCriterion("PROJ_UUID >=", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLessThan(String value) {
            addCriterion("PROJ_UUID <", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLessThanOrEqualTo(String value) {
            addCriterion("PROJ_UUID <=", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLike(String value) {
            addCriterion("PROJ_UUID like", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotLike(String value) {
            addCriterion("PROJ_UUID not like", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidIn(List<String> values) {
            addCriterion("PROJ_UUID in", values, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotIn(List<String> values) {
            addCriterion("PROJ_UUID not in", values, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidBetween(String value1, String value2) {
            addCriterion("PROJ_UUID between", value1, value2, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotBetween(String value1, String value2) {
            addCriterion("PROJ_UUID not between", value1, value2, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjPriceIsNull() {
            addCriterion("PROJ_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andProjPriceIsNotNull() {
            addCriterion("PROJ_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andProjPriceEqualTo(String value) {
            addCriterion("PROJ_PRICE =", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceNotEqualTo(String value) {
            addCriterion("PROJ_PRICE <>", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceGreaterThan(String value) {
            addCriterion("PROJ_PRICE >", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceGreaterThanOrEqualTo(String value) {
            addCriterion("PROJ_PRICE >=", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceLessThan(String value) {
            addCriterion("PROJ_PRICE <", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceLessThanOrEqualTo(String value) {
            addCriterion("PROJ_PRICE <=", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceLike(String value) {
            addCriterion("PROJ_PRICE like", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceNotLike(String value) {
            addCriterion("PROJ_PRICE not like", value, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceIn(List<String> values) {
            addCriterion("PROJ_PRICE in", values, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceNotIn(List<String> values) {
            addCriterion("PROJ_PRICE not in", values, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceBetween(String value1, String value2) {
            addCriterion("PROJ_PRICE between", value1, value2, "projPrice");
            return (Criteria) this;
        }

        public Criteria andProjPriceNotBetween(String value1, String value2) {
            addCriterion("PROJ_PRICE not between", value1, value2, "projPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceIsNull() {
            addCriterion("PERIMETER_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceIsNotNull() {
            addCriterion("PERIMETER_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceEqualTo(String value) {
            addCriterion("PERIMETER_PRICE =", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceNotEqualTo(String value) {
            addCriterion("PERIMETER_PRICE <>", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceGreaterThan(String value) {
            addCriterion("PERIMETER_PRICE >", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceGreaterThanOrEqualTo(String value) {
            addCriterion("PERIMETER_PRICE >=", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceLessThan(String value) {
            addCriterion("PERIMETER_PRICE <", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceLessThanOrEqualTo(String value) {
            addCriterion("PERIMETER_PRICE <=", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceLike(String value) {
            addCriterion("PERIMETER_PRICE like", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceNotLike(String value) {
            addCriterion("PERIMETER_PRICE not like", value, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceIn(List<String> values) {
            addCriterion("PERIMETER_PRICE in", values, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceNotIn(List<String> values) {
            addCriterion("PERIMETER_PRICE not in", values, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceBetween(String value1, String value2) {
            addCriterion("PERIMETER_PRICE between", value1, value2, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPerimeterPriceNotBetween(String value1, String value2) {
            addCriterion("PERIMETER_PRICE not between", value1, value2, "perimeterPrice");
            return (Criteria) this;
        }

        public Criteria andPriceDateIsNull() {
            addCriterion("PRICE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPriceDateIsNotNull() {
            addCriterion("PRICE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPriceDateEqualTo(String value) {
            addCriterion("PRICE_DATE =", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateNotEqualTo(String value) {
            addCriterion("PRICE_DATE <>", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateGreaterThan(String value) {
            addCriterion("PRICE_DATE >", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateGreaterThanOrEqualTo(String value) {
            addCriterion("PRICE_DATE >=", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateLessThan(String value) {
            addCriterion("PRICE_DATE <", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateLessThanOrEqualTo(String value) {
            addCriterion("PRICE_DATE <=", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateLike(String value) {
            addCriterion("PRICE_DATE like", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateNotLike(String value) {
            addCriterion("PRICE_DATE not like", value, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateIn(List<String> values) {
            addCriterion("PRICE_DATE in", values, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateNotIn(List<String> values) {
            addCriterion("PRICE_DATE not in", values, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateBetween(String value1, String value2) {
            addCriterion("PRICE_DATE between", value1, value2, "priceDate");
            return (Criteria) this;
        }

        public Criteria andPriceDateNotBetween(String value1, String value2) {
            addCriterion("PRICE_DATE not between", value1, value2, "priceDate");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCancelIsNull() {
            addCriterion("CANCEL is null");
            return (Criteria) this;
        }

        public Criteria andCancelIsNotNull() {
            addCriterion("CANCEL is not null");
            return (Criteria) this;
        }

        public Criteria andCancelEqualTo(String value) {
            addCriterion("CANCEL =", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotEqualTo(String value) {
            addCriterion("CANCEL <>", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThan(String value) {
            addCriterion("CANCEL >", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThanOrEqualTo(String value) {
            addCriterion("CANCEL >=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThan(String value) {
            addCriterion("CANCEL <", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThanOrEqualTo(String value) {
            addCriterion("CANCEL <=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLike(String value) {
            addCriterion("CANCEL like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotLike(String value) {
            addCriterion("CANCEL not like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelIn(List<String> values) {
            addCriterion("CANCEL in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotIn(List<String> values) {
            addCriterion("CANCEL not in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelBetween(String value1, String value2) {
            addCriterion("CANCEL between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotBetween(String value1, String value2) {
            addCriterion("CANCEL not between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("COMMENTS =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("COMMENTS <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("COMMENTS >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENTS >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("COMMENTS <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("COMMENTS <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("COMMENTS like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("COMMENTS not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("COMMENTS in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("COMMENTS not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("COMMENTS between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("COMMENTS not between", value1, value2, "comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_price
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_price
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}