package com.crowdfunding.pojo;

public class CrowdAnnouncement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_announcement.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_announcement.TITLE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_announcement.PUBLIST_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String publistDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_announcement.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_announcement.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_announcement.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_announcement.CONTENT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_announcement.UUID
     *
     * @return the value of crowd_announcement.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_announcement.UUID
     *
     * @param uuid the value for crowd_announcement.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_announcement.TITLE
     *
     * @return the value of crowd_announcement.TITLE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_announcement.TITLE
     *
     * @param title the value for crowd_announcement.TITLE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_announcement.PUBLIST_DATE
     *
     * @return the value of crowd_announcement.PUBLIST_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getPublistDate() {
        return publistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_announcement.PUBLIST_DATE
     *
     * @param publistDate the value for crowd_announcement.PUBLIST_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setPublistDate(String publistDate) {
        this.publistDate = publistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_announcement.TYPE
     *
     * @return the value of crowd_announcement.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_announcement.TYPE
     *
     * @param type the value for crowd_announcement.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_announcement.CANCEL
     *
     * @return the value of crowd_announcement.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_announcement.CANCEL
     *
     * @param cancel the value for crowd_announcement.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCancel(String cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_announcement.COMMENTS
     *
     * @return the value of crowd_announcement.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_announcement.COMMENTS
     *
     * @param comments the value for crowd_announcement.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_announcement.CONTENT
     *
     * @return the value of crowd_announcement.CONTENT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_announcement.CONTENT
     *
     * @param content the value for crowd_announcement.CONTENT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}