package com.crowdfunding.pojo;

import java.util.ArrayList;
import java.util.List;

public class CrowdImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public CrowdImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidIsNull() {
            addCriterion("PROJ_UUID is null");
            return (Criteria) this;
        }

        public Criteria andProjUuidIsNotNull() {
            addCriterion("PROJ_UUID is not null");
            return (Criteria) this;
        }

        public Criteria andProjUuidEqualTo(String value) {
            addCriterion("PROJ_UUID =", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotEqualTo(String value) {
            addCriterion("PROJ_UUID <>", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidGreaterThan(String value) {
            addCriterion("PROJ_UUID >", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidGreaterThanOrEqualTo(String value) {
            addCriterion("PROJ_UUID >=", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLessThan(String value) {
            addCriterion("PROJ_UUID <", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLessThanOrEqualTo(String value) {
            addCriterion("PROJ_UUID <=", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLike(String value) {
            addCriterion("PROJ_UUID like", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotLike(String value) {
            addCriterion("PROJ_UUID not like", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidIn(List<String> values) {
            addCriterion("PROJ_UUID in", values, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotIn(List<String> values) {
            addCriterion("PROJ_UUID not in", values, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidBetween(String value1, String value2) {
            addCriterion("PROJ_UUID between", value1, value2, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotBetween(String value1, String value2) {
            addCriterion("PROJ_UUID not between", value1, value2, "projUuid");
            return (Criteria) this;
        }

        public Criteria andImageContentIsNull() {
            addCriterion("IMAGE_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andImageContentIsNotNull() {
            addCriterion("IMAGE_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andImageContentEqualTo(String value) {
            addCriterion("IMAGE_CONTENT =", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentNotEqualTo(String value) {
            addCriterion("IMAGE_CONTENT <>", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentGreaterThan(String value) {
            addCriterion("IMAGE_CONTENT >", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_CONTENT >=", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentLessThan(String value) {
            addCriterion("IMAGE_CONTENT <", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_CONTENT <=", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentLike(String value) {
            addCriterion("IMAGE_CONTENT like", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentNotLike(String value) {
            addCriterion("IMAGE_CONTENT not like", value, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentIn(List<String> values) {
            addCriterion("IMAGE_CONTENT in", values, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentNotIn(List<String> values) {
            addCriterion("IMAGE_CONTENT not in", values, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentBetween(String value1, String value2) {
            addCriterion("IMAGE_CONTENT between", value1, value2, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageContentNotBetween(String value1, String value2) {
            addCriterion("IMAGE_CONTENT not between", value1, value2, "imageContent");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNull() {
            addCriterion("IMAGE_URL is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNotNull() {
            addCriterion("IMAGE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlEqualTo(String value) {
            addCriterion("IMAGE_URL =", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotEqualTo(String value) {
            addCriterion("IMAGE_URL <>", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThan(String value) {
            addCriterion("IMAGE_URL >", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_URL >=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThan(String value) {
            addCriterion("IMAGE_URL <", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_URL <=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLike(String value) {
            addCriterion("IMAGE_URL like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotLike(String value) {
            addCriterion("IMAGE_URL not like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIn(List<String> values) {
            addCriterion("IMAGE_URL in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotIn(List<String> values) {
            addCriterion("IMAGE_URL not in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlBetween(String value1, String value2) {
            addCriterion("IMAGE_URL between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotBetween(String value1, String value2) {
            addCriterion("IMAGE_URL not between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageTypeIsNull() {
            addCriterion("IMAGE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andImageTypeIsNotNull() {
            addCriterion("IMAGE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andImageTypeEqualTo(String value) {
            addCriterion("IMAGE_TYPE =", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeNotEqualTo(String value) {
            addCriterion("IMAGE_TYPE <>", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeGreaterThan(String value) {
            addCriterion("IMAGE_TYPE >", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_TYPE >=", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeLessThan(String value) {
            addCriterion("IMAGE_TYPE <", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_TYPE <=", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeLike(String value) {
            addCriterion("IMAGE_TYPE like", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeNotLike(String value) {
            addCriterion("IMAGE_TYPE not like", value, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeIn(List<String> values) {
            addCriterion("IMAGE_TYPE in", values, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeNotIn(List<String> values) {
            addCriterion("IMAGE_TYPE not in", values, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeBetween(String value1, String value2) {
            addCriterion("IMAGE_TYPE between", value1, value2, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageTypeNotBetween(String value1, String value2) {
            addCriterion("IMAGE_TYPE not between", value1, value2, "imageType");
            return (Criteria) this;
        }

        public Criteria andImageSeqIsNull() {
            addCriterion("IMAGE_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andImageSeqIsNotNull() {
            addCriterion("IMAGE_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andImageSeqEqualTo(String value) {
            addCriterion("IMAGE_SEQ =", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqNotEqualTo(String value) {
            addCriterion("IMAGE_SEQ <>", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqGreaterThan(String value) {
            addCriterion("IMAGE_SEQ >", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_SEQ >=", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqLessThan(String value) {
            addCriterion("IMAGE_SEQ <", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_SEQ <=", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqLike(String value) {
            addCriterion("IMAGE_SEQ like", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqNotLike(String value) {
            addCriterion("IMAGE_SEQ not like", value, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqIn(List<String> values) {
            addCriterion("IMAGE_SEQ in", values, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqNotIn(List<String> values) {
            addCriterion("IMAGE_SEQ not in", values, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqBetween(String value1, String value2) {
            addCriterion("IMAGE_SEQ between", value1, value2, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andImageSeqNotBetween(String value1, String value2) {
            addCriterion("IMAGE_SEQ not between", value1, value2, "imageSeq");
            return (Criteria) this;
        }

        public Criteria andIsindexIsNull() {
            addCriterion("ISINDEX is null");
            return (Criteria) this;
        }

        public Criteria andIsindexIsNotNull() {
            addCriterion("ISINDEX is not null");
            return (Criteria) this;
        }

        public Criteria andIsindexEqualTo(String value) {
            addCriterion("ISINDEX =", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexNotEqualTo(String value) {
            addCriterion("ISINDEX <>", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexGreaterThan(String value) {
            addCriterion("ISINDEX >", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexGreaterThanOrEqualTo(String value) {
            addCriterion("ISINDEX >=", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexLessThan(String value) {
            addCriterion("ISINDEX <", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexLessThanOrEqualTo(String value) {
            addCriterion("ISINDEX <=", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexLike(String value) {
            addCriterion("ISINDEX like", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexNotLike(String value) {
            addCriterion("ISINDEX not like", value, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexIn(List<String> values) {
            addCriterion("ISINDEX in", values, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexNotIn(List<String> values) {
            addCriterion("ISINDEX not in", values, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexBetween(String value1, String value2) {
            addCriterion("ISINDEX between", value1, value2, "isindex");
            return (Criteria) this;
        }

        public Criteria andIsindexNotBetween(String value1, String value2) {
            addCriterion("ISINDEX not between", value1, value2, "isindex");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCancelIsNull() {
            addCriterion("CANCEL is null");
            return (Criteria) this;
        }

        public Criteria andCancelIsNotNull() {
            addCriterion("CANCEL is not null");
            return (Criteria) this;
        }

        public Criteria andCancelEqualTo(String value) {
            addCriterion("CANCEL =", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotEqualTo(String value) {
            addCriterion("CANCEL <>", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThan(String value) {
            addCriterion("CANCEL >", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThanOrEqualTo(String value) {
            addCriterion("CANCEL >=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThan(String value) {
            addCriterion("CANCEL <", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThanOrEqualTo(String value) {
            addCriterion("CANCEL <=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLike(String value) {
            addCriterion("CANCEL like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotLike(String value) {
            addCriterion("CANCEL not like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelIn(List<String> values) {
            addCriterion("CANCEL in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotIn(List<String> values) {
            addCriterion("CANCEL not in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelBetween(String value1, String value2) {
            addCriterion("CANCEL between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotBetween(String value1, String value2) {
            addCriterion("CANCEL not between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("COMMENTS =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("COMMENTS <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("COMMENTS >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENTS >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("COMMENTS <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("COMMENTS <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("COMMENTS like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("COMMENTS not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("COMMENTS in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("COMMENTS not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("COMMENTS between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("COMMENTS not between", value1, value2, "comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_image
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_image
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}