package com.crowdfunding.pojo;

import java.util.ArrayList;
import java.util.List;

public class CrowdFaqExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public CrowdFaqExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andConsultDateIsNull() {
            addCriterion("CONSULT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andConsultDateIsNotNull() {
            addCriterion("CONSULT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andConsultDateEqualTo(String value) {
            addCriterion("CONSULT_DATE =", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateNotEqualTo(String value) {
            addCriterion("CONSULT_DATE <>", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateGreaterThan(String value) {
            addCriterion("CONSULT_DATE >", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateGreaterThanOrEqualTo(String value) {
            addCriterion("CONSULT_DATE >=", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateLessThan(String value) {
            addCriterion("CONSULT_DATE <", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateLessThanOrEqualTo(String value) {
            addCriterion("CONSULT_DATE <=", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateLike(String value) {
            addCriterion("CONSULT_DATE like", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateNotLike(String value) {
            addCriterion("CONSULT_DATE not like", value, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateIn(List<String> values) {
            addCriterion("CONSULT_DATE in", values, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateNotIn(List<String> values) {
            addCriterion("CONSULT_DATE not in", values, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateBetween(String value1, String value2) {
            addCriterion("CONSULT_DATE between", value1, value2, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultDateNotBetween(String value1, String value2) {
            addCriterion("CONSULT_DATE not between", value1, value2, "consultDate");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameIsNull() {
            addCriterion("CONSULT_USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameIsNotNull() {
            addCriterion("CONSULT_USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameEqualTo(String value) {
            addCriterion("CONSULT_USERNAME =", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameNotEqualTo(String value) {
            addCriterion("CONSULT_USERNAME <>", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameGreaterThan(String value) {
            addCriterion("CONSULT_USERNAME >", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("CONSULT_USERNAME >=", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameLessThan(String value) {
            addCriterion("CONSULT_USERNAME <", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameLessThanOrEqualTo(String value) {
            addCriterion("CONSULT_USERNAME <=", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameLike(String value) {
            addCriterion("CONSULT_USERNAME like", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameNotLike(String value) {
            addCriterion("CONSULT_USERNAME not like", value, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameIn(List<String> values) {
            addCriterion("CONSULT_USERNAME in", values, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameNotIn(List<String> values) {
            addCriterion("CONSULT_USERNAME not in", values, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameBetween(String value1, String value2) {
            addCriterion("CONSULT_USERNAME between", value1, value2, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andConsultUsernameNotBetween(String value1, String value2) {
            addCriterion("CONSULT_USERNAME not between", value1, value2, "consultUsername");
            return (Criteria) this;
        }

        public Criteria andIsureIsNull() {
            addCriterion("ISURE is null");
            return (Criteria) this;
        }

        public Criteria andIsureIsNotNull() {
            addCriterion("ISURE is not null");
            return (Criteria) this;
        }

        public Criteria andIsureEqualTo(String value) {
            addCriterion("ISURE =", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureNotEqualTo(String value) {
            addCriterion("ISURE <>", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureGreaterThan(String value) {
            addCriterion("ISURE >", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureGreaterThanOrEqualTo(String value) {
            addCriterion("ISURE >=", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureLessThan(String value) {
            addCriterion("ISURE <", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureLessThanOrEqualTo(String value) {
            addCriterion("ISURE <=", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureLike(String value) {
            addCriterion("ISURE like", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureNotLike(String value) {
            addCriterion("ISURE not like", value, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureIn(List<String> values) {
            addCriterion("ISURE in", values, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureNotIn(List<String> values) {
            addCriterion("ISURE not in", values, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureBetween(String value1, String value2) {
            addCriterion("ISURE between", value1, value2, "isure");
            return (Criteria) this;
        }

        public Criteria andIsureNotBetween(String value1, String value2) {
            addCriterion("ISURE not between", value1, value2, "isure");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberIsNull() {
            addCriterion("CONSULT_PHONENUMBER is null");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberIsNotNull() {
            addCriterion("CONSULT_PHONENUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberEqualTo(String value) {
            addCriterion("CONSULT_PHONENUMBER =", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberNotEqualTo(String value) {
            addCriterion("CONSULT_PHONENUMBER <>", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberGreaterThan(String value) {
            addCriterion("CONSULT_PHONENUMBER >", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberGreaterThanOrEqualTo(String value) {
            addCriterion("CONSULT_PHONENUMBER >=", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberLessThan(String value) {
            addCriterion("CONSULT_PHONENUMBER <", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberLessThanOrEqualTo(String value) {
            addCriterion("CONSULT_PHONENUMBER <=", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberLike(String value) {
            addCriterion("CONSULT_PHONENUMBER like", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberNotLike(String value) {
            addCriterion("CONSULT_PHONENUMBER not like", value, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberIn(List<String> values) {
            addCriterion("CONSULT_PHONENUMBER in", values, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberNotIn(List<String> values) {
            addCriterion("CONSULT_PHONENUMBER not in", values, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberBetween(String value1, String value2) {
            addCriterion("CONSULT_PHONENUMBER between", value1, value2, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultPhonenumberNotBetween(String value1, String value2) {
            addCriterion("CONSULT_PHONENUMBER not between", value1, value2, "consultPhonenumber");
            return (Criteria) this;
        }

        public Criteria andConsultTypeIsNull() {
            addCriterion("CONSULT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andConsultTypeIsNotNull() {
            addCriterion("CONSULT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andConsultTypeEqualTo(String value) {
            addCriterion("CONSULT_TYPE =", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeNotEqualTo(String value) {
            addCriterion("CONSULT_TYPE <>", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeGreaterThan(String value) {
            addCriterion("CONSULT_TYPE >", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CONSULT_TYPE >=", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeLessThan(String value) {
            addCriterion("CONSULT_TYPE <", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeLessThanOrEqualTo(String value) {
            addCriterion("CONSULT_TYPE <=", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeLike(String value) {
            addCriterion("CONSULT_TYPE like", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeNotLike(String value) {
            addCriterion("CONSULT_TYPE not like", value, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeIn(List<String> values) {
            addCriterion("CONSULT_TYPE in", values, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeNotIn(List<String> values) {
            addCriterion("CONSULT_TYPE not in", values, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeBetween(String value1, String value2) {
            addCriterion("CONSULT_TYPE between", value1, value2, "consultType");
            return (Criteria) this;
        }

        public Criteria andConsultTypeNotBetween(String value1, String value2) {
            addCriterion("CONSULT_TYPE not between", value1, value2, "consultType");
            return (Criteria) this;
        }

        public Criteria andCancelIsNull() {
            addCriterion("CANCEL is null");
            return (Criteria) this;
        }

        public Criteria andCancelIsNotNull() {
            addCriterion("CANCEL is not null");
            return (Criteria) this;
        }

        public Criteria andCancelEqualTo(String value) {
            addCriterion("CANCEL =", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotEqualTo(String value) {
            addCriterion("CANCEL <>", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThan(String value) {
            addCriterion("CANCEL >", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThanOrEqualTo(String value) {
            addCriterion("CANCEL >=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThan(String value) {
            addCriterion("CANCEL <", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThanOrEqualTo(String value) {
            addCriterion("CANCEL <=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLike(String value) {
            addCriterion("CANCEL like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotLike(String value) {
            addCriterion("CANCEL not like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelIn(List<String> values) {
            addCriterion("CANCEL in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotIn(List<String> values) {
            addCriterion("CANCEL not in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelBetween(String value1, String value2) {
            addCriterion("CANCEL between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotBetween(String value1, String value2) {
            addCriterion("CANCEL not between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("COMMENTS =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("COMMENTS <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("COMMENTS >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENTS >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("COMMENTS <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("COMMENTS <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("COMMENTS like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("COMMENTS not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("COMMENTS in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("COMMENTS not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("COMMENTS between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("COMMENTS not between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andConsultType2IsNull() {
            addCriterion("CONSULT_TYPE2 is null");
            return (Criteria) this;
        }

        public Criteria andConsultType2IsNotNull() {
            addCriterion("CONSULT_TYPE2 is not null");
            return (Criteria) this;
        }

        public Criteria andConsultType2EqualTo(String value) {
            addCriterion("CONSULT_TYPE2 =", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2NotEqualTo(String value) {
            addCriterion("CONSULT_TYPE2 <>", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2GreaterThan(String value) {
            addCriterion("CONSULT_TYPE2 >", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2GreaterThanOrEqualTo(String value) {
            addCriterion("CONSULT_TYPE2 >=", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2LessThan(String value) {
            addCriterion("CONSULT_TYPE2 <", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2LessThanOrEqualTo(String value) {
            addCriterion("CONSULT_TYPE2 <=", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2Like(String value) {
            addCriterion("CONSULT_TYPE2 like", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2NotLike(String value) {
            addCriterion("CONSULT_TYPE2 not like", value, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2In(List<String> values) {
            addCriterion("CONSULT_TYPE2 in", values, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2NotIn(List<String> values) {
            addCriterion("CONSULT_TYPE2 not in", values, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2Between(String value1, String value2) {
            addCriterion("CONSULT_TYPE2 between", value1, value2, "consultType2");
            return (Criteria) this;
        }

        public Criteria andConsultType2NotBetween(String value1, String value2) {
            addCriterion("CONSULT_TYPE2 not between", value1, value2, "consultType2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_faq
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crowd_faq
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}