package com.crowdfunding.pojo;

public class CrowdImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String projUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.IMAGE_CONTENT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String imageContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.IMAGE_URL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.IMAGE_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String imageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.IMAGE_SEQ
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String imageSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.ISINDEX
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String isindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.CREATE_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_image.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.UUID
     *
     * @return the value of crowd_image.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.UUID
     *
     * @param uuid the value for crowd_image.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.PROJ_UUID
     *
     * @return the value of crowd_image.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getProjUuid() {
        return projUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.PROJ_UUID
     *
     * @param projUuid the value for crowd_image.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setProjUuid(String projUuid) {
        this.projUuid = projUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.IMAGE_CONTENT
     *
     * @return the value of crowd_image.IMAGE_CONTENT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getImageContent() {
        return imageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.IMAGE_CONTENT
     *
     * @param imageContent the value for crowd_image.IMAGE_CONTENT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setImageContent(String imageContent) {
        this.imageContent = imageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.IMAGE_URL
     *
     * @return the value of crowd_image.IMAGE_URL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.IMAGE_URL
     *
     * @param imageUrl the value for crowd_image.IMAGE_URL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.IMAGE_TYPE
     *
     * @return the value of crowd_image.IMAGE_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.IMAGE_TYPE
     *
     * @param imageType the value for crowd_image.IMAGE_TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.IMAGE_SEQ
     *
     * @return the value of crowd_image.IMAGE_SEQ
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getImageSeq() {
        return imageSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.IMAGE_SEQ
     *
     * @param imageSeq the value for crowd_image.IMAGE_SEQ
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setImageSeq(String imageSeq) {
        this.imageSeq = imageSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.ISINDEX
     *
     * @return the value of crowd_image.ISINDEX
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getIsindex() {
        return isindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.ISINDEX
     *
     * @param isindex the value for crowd_image.ISINDEX
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setIsindex(String isindex) {
        this.isindex = isindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.CREATE_DATE
     *
     * @return the value of crowd_image.CREATE_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.CREATE_DATE
     *
     * @param createDate the value for crowd_image.CREATE_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.CANCEL
     *
     * @return the value of crowd_image.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.CANCEL
     *
     * @param cancel the value for crowd_image.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCancel(String cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_image.COMMENTS
     *
     * @return the value of crowd_image.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_image.COMMENTS
     *
     * @param comments the value for crowd_image.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}