package com.crowdfunding.pojo;

public class CrowdTransJournal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.uuid
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String journal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.order_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.trans_code
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String transCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.user_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.related_user_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String relatedUserNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.trans_amt
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String transAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.divide_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String divideInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.err_msg
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String errMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.trans_datetime
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String transDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.remark
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.mer_priv
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String merPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.user_name
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.status
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.account_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String accountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_trans_journal.reserve
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String reserve;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.uuid
     *
     * @return the value of crowd_trans_journal.uuid
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.uuid
     *
     * @param uuid the value for crowd_trans_journal.uuid
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.journal
     *
     * @return the value of crowd_trans_journal.journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getJournal() {
        return journal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.journal
     *
     * @param journal the value for crowd_trans_journal.journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setJournal(String journal) {
        this.journal = journal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.order_no
     *
     * @return the value of crowd_trans_journal.order_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.order_no
     *
     * @param orderNo the value for crowd_trans_journal.order_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.trans_code
     *
     * @return the value of crowd_trans_journal.trans_code
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getTransCode() {
        return transCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.trans_code
     *
     * @param transCode the value for crowd_trans_journal.trans_code
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setTransCode(String transCode) {
        this.transCode = transCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.user_no
     *
     * @return the value of crowd_trans_journal.user_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.user_no
     *
     * @param userNo the value for crowd_trans_journal.user_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.related_user_no
     *
     * @return the value of crowd_trans_journal.related_user_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getRelatedUserNo() {
        return relatedUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.related_user_no
     *
     * @param relatedUserNo the value for crowd_trans_journal.related_user_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setRelatedUserNo(String relatedUserNo) {
        this.relatedUserNo = relatedUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.trans_amt
     *
     * @return the value of crowd_trans_journal.trans_amt
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getTransAmt() {
        return transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.trans_amt
     *
     * @param transAmt the value for crowd_trans_journal.trans_amt
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setTransAmt(String transAmt) {
        this.transAmt = transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.divide_info
     *
     * @return the value of crowd_trans_journal.divide_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getDivideInfo() {
        return divideInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.divide_info
     *
     * @param divideInfo the value for crowd_trans_journal.divide_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setDivideInfo(String divideInfo) {
        this.divideInfo = divideInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.err_msg
     *
     * @return the value of crowd_trans_journal.err_msg
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.err_msg
     *
     * @param errMsg the value for crowd_trans_journal.err_msg
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.trans_datetime
     *
     * @return the value of crowd_trans_journal.trans_datetime
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getTransDatetime() {
        return transDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.trans_datetime
     *
     * @param transDatetime the value for crowd_trans_journal.trans_datetime
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setTransDatetime(String transDatetime) {
        this.transDatetime = transDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.remark
     *
     * @return the value of crowd_trans_journal.remark
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.remark
     *
     * @param remark the value for crowd_trans_journal.remark
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.mer_priv
     *
     * @return the value of crowd_trans_journal.mer_priv
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getMerPriv() {
        return merPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.mer_priv
     *
     * @param merPriv the value for crowd_trans_journal.mer_priv
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setMerPriv(String merPriv) {
        this.merPriv = merPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.user_name
     *
     * @return the value of crowd_trans_journal.user_name
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.user_name
     *
     * @param userName the value for crowd_trans_journal.user_name
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.status
     *
     * @return the value of crowd_trans_journal.status
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.status
     *
     * @param status the value for crowd_trans_journal.status
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.account_no
     *
     * @return the value of crowd_trans_journal.account_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.account_no
     *
     * @param accountNo the value for crowd_trans_journal.account_no
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_trans_journal.reserve
     *
     * @return the value of crowd_trans_journal.reserve
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_trans_journal.reserve
     *
     * @param reserve the value for crowd_trans_journal.reserve
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }
}