package com.crowdfunding.pojo;

public class CrowdFavorer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_favorer.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_favorer.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_favorer.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String projUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_favorer.FAVORER_DATETIME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String favorerDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_favorer.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String accountUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_favorer.UUID
     *
     * @return the value of crowd_favorer.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_favorer.UUID
     *
     * @param uuid the value for crowd_favorer.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_favorer.USER_UUID
     *
     * @return the value of crowd_favorer.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_favorer.USER_UUID
     *
     * @param userUuid the value for crowd_favorer.USER_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_favorer.PROJ_UUID
     *
     * @return the value of crowd_favorer.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getProjUuid() {
        return projUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_favorer.PROJ_UUID
     *
     * @param projUuid the value for crowd_favorer.PROJ_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setProjUuid(String projUuid) {
        this.projUuid = projUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_favorer.FAVORER_DATETIME
     *
     * @return the value of crowd_favorer.FAVORER_DATETIME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getFavorerDatetime() {
        return favorerDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_favorer.FAVORER_DATETIME
     *
     * @param favorerDatetime the value for crowd_favorer.FAVORER_DATETIME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setFavorerDatetime(String favorerDatetime) {
        this.favorerDatetime = favorerDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_favorer.ACCOUNT_UUID
     *
     * @return the value of crowd_favorer.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getAccountUuid() {
        return accountUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_favorer.ACCOUNT_UUID
     *
     * @param accountUuid the value for crowd_favorer.ACCOUNT_UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setAccountUuid(String accountUuid) {
        this.accountUuid = accountUuid;
    }
}