package com.crowdfunding.pojo;

import java.util.ArrayList;
import java.util.List;

public class ProjTenancyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public ProjTenancyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidIsNull() {
            addCriterion("PROJ_UUID is null");
            return (Criteria) this;
        }

        public Criteria andProjUuidIsNotNull() {
            addCriterion("PROJ_UUID is not null");
            return (Criteria) this;
        }

        public Criteria andProjUuidEqualTo(String value) {
            addCriterion("PROJ_UUID =", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotEqualTo(String value) {
            addCriterion("PROJ_UUID <>", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidGreaterThan(String value) {
            addCriterion("PROJ_UUID >", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidGreaterThanOrEqualTo(String value) {
            addCriterion("PROJ_UUID >=", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLessThan(String value) {
            addCriterion("PROJ_UUID <", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLessThanOrEqualTo(String value) {
            addCriterion("PROJ_UUID <=", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidLike(String value) {
            addCriterion("PROJ_UUID like", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotLike(String value) {
            addCriterion("PROJ_UUID not like", value, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidIn(List<String> values) {
            addCriterion("PROJ_UUID in", values, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotIn(List<String> values) {
            addCriterion("PROJ_UUID not in", values, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidBetween(String value1, String value2) {
            addCriterion("PROJ_UUID between", value1, value2, "projUuid");
            return (Criteria) this;
        }

        public Criteria andProjUuidNotBetween(String value1, String value2) {
            addCriterion("PROJ_UUID not between", value1, value2, "projUuid");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNull() {
            addCriterion("OPERATION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNotNull() {
            addCriterion("OPERATION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeEqualTo(String value) {
            addCriterion("OPERATION_TYPE =", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotEqualTo(String value) {
            addCriterion("OPERATION_TYPE <>", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThan(String value) {
            addCriterion("OPERATION_TYPE >", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATION_TYPE >=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThan(String value) {
            addCriterion("OPERATION_TYPE <", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThanOrEqualTo(String value) {
            addCriterion("OPERATION_TYPE <=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLike(String value) {
            addCriterion("OPERATION_TYPE like", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotLike(String value) {
            addCriterion("OPERATION_TYPE not like", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIn(List<String> values) {
            addCriterion("OPERATION_TYPE in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotIn(List<String> values) {
            addCriterion("OPERATION_TYPE not in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeBetween(String value1, String value2) {
            addCriterion("OPERATION_TYPE between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotBetween(String value1, String value2) {
            addCriterion("OPERATION_TYPE not between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitIsNull() {
            addCriterion("TENANCY_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitIsNotNull() {
            addCriterion("TENANCY_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitEqualTo(String value) {
            addCriterion("TENANCY_UNIT =", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitNotEqualTo(String value) {
            addCriterion("TENANCY_UNIT <>", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitGreaterThan(String value) {
            addCriterion("TENANCY_UNIT >", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitGreaterThanOrEqualTo(String value) {
            addCriterion("TENANCY_UNIT >=", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitLessThan(String value) {
            addCriterion("TENANCY_UNIT <", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitLessThanOrEqualTo(String value) {
            addCriterion("TENANCY_UNIT <=", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitLike(String value) {
            addCriterion("TENANCY_UNIT like", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitNotLike(String value) {
            addCriterion("TENANCY_UNIT not like", value, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitIn(List<String> values) {
            addCriterion("TENANCY_UNIT in", values, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitNotIn(List<String> values) {
            addCriterion("TENANCY_UNIT not in", values, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitBetween(String value1, String value2) {
            addCriterion("TENANCY_UNIT between", value1, value2, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyUnitNotBetween(String value1, String value2) {
            addCriterion("TENANCY_UNIT not between", value1, value2, "tenancyUnit");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateIsNull() {
            addCriterion("TENANCY_STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateIsNotNull() {
            addCriterion("TENANCY_STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateEqualTo(String value) {
            addCriterion("TENANCY_STARTDATE =", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateNotEqualTo(String value) {
            addCriterion("TENANCY_STARTDATE <>", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateGreaterThan(String value) {
            addCriterion("TENANCY_STARTDATE >", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("TENANCY_STARTDATE >=", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateLessThan(String value) {
            addCriterion("TENANCY_STARTDATE <", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateLessThanOrEqualTo(String value) {
            addCriterion("TENANCY_STARTDATE <=", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateLike(String value) {
            addCriterion("TENANCY_STARTDATE like", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateNotLike(String value) {
            addCriterion("TENANCY_STARTDATE not like", value, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateIn(List<String> values) {
            addCriterion("TENANCY_STARTDATE in", values, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateNotIn(List<String> values) {
            addCriterion("TENANCY_STARTDATE not in", values, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateBetween(String value1, String value2) {
            addCriterion("TENANCY_STARTDATE between", value1, value2, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStartdateNotBetween(String value1, String value2) {
            addCriterion("TENANCY_STARTDATE not between", value1, value2, "tenancyStartdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateIsNull() {
            addCriterion("TENANCY_STOPDATE is null");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateIsNotNull() {
            addCriterion("TENANCY_STOPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateEqualTo(String value) {
            addCriterion("TENANCY_STOPDATE =", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateNotEqualTo(String value) {
            addCriterion("TENANCY_STOPDATE <>", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateGreaterThan(String value) {
            addCriterion("TENANCY_STOPDATE >", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateGreaterThanOrEqualTo(String value) {
            addCriterion("TENANCY_STOPDATE >=", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateLessThan(String value) {
            addCriterion("TENANCY_STOPDATE <", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateLessThanOrEqualTo(String value) {
            addCriterion("TENANCY_STOPDATE <=", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateLike(String value) {
            addCriterion("TENANCY_STOPDATE like", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateNotLike(String value) {
            addCriterion("TENANCY_STOPDATE not like", value, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateIn(List<String> values) {
            addCriterion("TENANCY_STOPDATE in", values, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateNotIn(List<String> values) {
            addCriterion("TENANCY_STOPDATE not in", values, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateBetween(String value1, String value2) {
            addCriterion("TENANCY_STOPDATE between", value1, value2, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyStopdateNotBetween(String value1, String value2) {
            addCriterion("TENANCY_STOPDATE not between", value1, value2, "tenancyStopdate");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountIsNull() {
            addCriterion("TENANCY_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountIsNotNull() {
            addCriterion("TENANCY_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountEqualTo(String value) {
            addCriterion("TENANCY_AMOUNT =", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountNotEqualTo(String value) {
            addCriterion("TENANCY_AMOUNT <>", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountGreaterThan(String value) {
            addCriterion("TENANCY_AMOUNT >", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountGreaterThanOrEqualTo(String value) {
            addCriterion("TENANCY_AMOUNT >=", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountLessThan(String value) {
            addCriterion("TENANCY_AMOUNT <", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountLessThanOrEqualTo(String value) {
            addCriterion("TENANCY_AMOUNT <=", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountLike(String value) {
            addCriterion("TENANCY_AMOUNT like", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountNotLike(String value) {
            addCriterion("TENANCY_AMOUNT not like", value, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountIn(List<String> values) {
            addCriterion("TENANCY_AMOUNT in", values, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountNotIn(List<String> values) {
            addCriterion("TENANCY_AMOUNT not in", values, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountBetween(String value1, String value2) {
            addCriterion("TENANCY_AMOUNT between", value1, value2, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andTenancyAmountNotBetween(String value1, String value2) {
            addCriterion("TENANCY_AMOUNT not between", value1, value2, "tenancyAmount");
            return (Criteria) this;
        }

        public Criteria andCancelIsNull() {
            addCriterion("CANCEL is null");
            return (Criteria) this;
        }

        public Criteria andCancelIsNotNull() {
            addCriterion("CANCEL is not null");
            return (Criteria) this;
        }

        public Criteria andCancelEqualTo(String value) {
            addCriterion("CANCEL =", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotEqualTo(String value) {
            addCriterion("CANCEL <>", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThan(String value) {
            addCriterion("CANCEL >", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelGreaterThanOrEqualTo(String value) {
            addCriterion("CANCEL >=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThan(String value) {
            addCriterion("CANCEL <", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLessThanOrEqualTo(String value) {
            addCriterion("CANCEL <=", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelLike(String value) {
            addCriterion("CANCEL like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotLike(String value) {
            addCriterion("CANCEL not like", value, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelIn(List<String> values) {
            addCriterion("CANCEL in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotIn(List<String> values) {
            addCriterion("CANCEL not in", values, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelBetween(String value1, String value2) {
            addCriterion("CANCEL between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCancelNotBetween(String value1, String value2) {
            addCriterion("CANCEL not between", value1, value2, "cancel");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("COMMENTS =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("COMMENTS <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("COMMENTS >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENTS >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("COMMENTS <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("COMMENTS <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("COMMENTS like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("COMMENTS not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("COMMENTS in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("COMMENTS not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("COMMENTS between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("COMMENTS not between", value1, value2, "comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_tenancy
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_tenancy
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}