package com.crowdfunding.pojo;

public class RegistrationUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.NICKNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.SEX
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.IDCARD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.PHONENUMBER
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.PASSWORD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.EMAIL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.EXTRACTPASSWORD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String extractpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.BIRTHDAY
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.EDUCATION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.SCHOOLNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String schoolname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.WEDLOCK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String wedlock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.ADDRESS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.COMPANY_TRADE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String companyTrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.COMPANY_SCALE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String companyScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.MONTHLY_INCOME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String monthlyIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.POSITION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.CREATE_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.CORP_NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.CORP_ADDR
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String corpAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.LEGAL_PERSON
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.REG_AMT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String regAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.CORP_TEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String corpTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.BUSINESS_LICENSE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String businessLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.PROJ_BANK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String projBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.GUARANTEE_ORG
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String guaranteeOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.SUPERVISORY_ORG
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String supervisoryOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.USERNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.USRCUSTID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String usrcustid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_user.BUSINESS_SCOPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String businessScope;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.UUID
     *
     * @return the value of registration_user.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.UUID
     *
     * @param uuid the value for registration_user.UUID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.NICKNAME
     *
     * @return the value of registration_user.NICKNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.NICKNAME
     *
     * @param nickname the value for registration_user.NICKNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.NAME
     *
     * @return the value of registration_user.NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.NAME
     *
     * @param name the value for registration_user.NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.SEX
     *
     * @return the value of registration_user.SEX
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.SEX
     *
     * @param sex the value for registration_user.SEX
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.IDCARD
     *
     * @return the value of registration_user.IDCARD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.IDCARD
     *
     * @param idcard the value for registration_user.IDCARD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.PHONENUMBER
     *
     * @return the value of registration_user.PHONENUMBER
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.PHONENUMBER
     *
     * @param phonenumber the value for registration_user.PHONENUMBER
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.PASSWORD
     *
     * @return the value of registration_user.PASSWORD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.PASSWORD
     *
     * @param password the value for registration_user.PASSWORD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.EMAIL
     *
     * @return the value of registration_user.EMAIL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.EMAIL
     *
     * @param email the value for registration_user.EMAIL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.EXTRACTPASSWORD
     *
     * @return the value of registration_user.EXTRACTPASSWORD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getExtractpassword() {
        return extractpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.EXTRACTPASSWORD
     *
     * @param extractpassword the value for registration_user.EXTRACTPASSWORD
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setExtractpassword(String extractpassword) {
        this.extractpassword = extractpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.BIRTHDAY
     *
     * @return the value of registration_user.BIRTHDAY
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.BIRTHDAY
     *
     * @param birthday the value for registration_user.BIRTHDAY
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.EDUCATION
     *
     * @return the value of registration_user.EDUCATION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.EDUCATION
     *
     * @param education the value for registration_user.EDUCATION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.SCHOOLNAME
     *
     * @return the value of registration_user.SCHOOLNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getSchoolname() {
        return schoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.SCHOOLNAME
     *
     * @param schoolname the value for registration_user.SCHOOLNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.WEDLOCK
     *
     * @return the value of registration_user.WEDLOCK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getWedlock() {
        return wedlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.WEDLOCK
     *
     * @param wedlock the value for registration_user.WEDLOCK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setWedlock(String wedlock) {
        this.wedlock = wedlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.ADDRESS
     *
     * @return the value of registration_user.ADDRESS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.ADDRESS
     *
     * @param address the value for registration_user.ADDRESS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.COMPANY_TRADE
     *
     * @return the value of registration_user.COMPANY_TRADE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCompanyTrade() {
        return companyTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.COMPANY_TRADE
     *
     * @param companyTrade the value for registration_user.COMPANY_TRADE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCompanyTrade(String companyTrade) {
        this.companyTrade = companyTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.COMPANY_SCALE
     *
     * @return the value of registration_user.COMPANY_SCALE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCompanyScale() {
        return companyScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.COMPANY_SCALE
     *
     * @param companyScale the value for registration_user.COMPANY_SCALE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCompanyScale(String companyScale) {
        this.companyScale = companyScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.MONTHLY_INCOME
     *
     * @return the value of registration_user.MONTHLY_INCOME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getMonthlyIncome() {
        return monthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.MONTHLY_INCOME
     *
     * @param monthlyIncome the value for registration_user.MONTHLY_INCOME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setMonthlyIncome(String monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.POSITION
     *
     * @return the value of registration_user.POSITION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.POSITION
     *
     * @param position the value for registration_user.POSITION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.CREATE_DATE
     *
     * @return the value of registration_user.CREATE_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.CREATE_DATE
     *
     * @param createDate the value for registration_user.CREATE_DATE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.TYPE
     *
     * @return the value of registration_user.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.TYPE
     *
     * @param type the value for registration_user.TYPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.CANCEL
     *
     * @return the value of registration_user.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.CANCEL
     *
     * @param cancel the value for registration_user.CANCEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCancel(String cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.COMMENTS
     *
     * @return the value of registration_user.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.COMMENTS
     *
     * @param comments the value for registration_user.COMMENTS
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.CORP_NAME
     *
     * @return the value of registration_user.CORP_NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.CORP_NAME
     *
     * @param corpName the value for registration_user.CORP_NAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.CORP_ADDR
     *
     * @return the value of registration_user.CORP_ADDR
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCorpAddr() {
        return corpAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.CORP_ADDR
     *
     * @param corpAddr the value for registration_user.CORP_ADDR
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCorpAddr(String corpAddr) {
        this.corpAddr = corpAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.LEGAL_PERSON
     *
     * @return the value of registration_user.LEGAL_PERSON
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.LEGAL_PERSON
     *
     * @param legalPerson the value for registration_user.LEGAL_PERSON
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.REG_AMT
     *
     * @return the value of registration_user.REG_AMT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getRegAmt() {
        return regAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.REG_AMT
     *
     * @param regAmt the value for registration_user.REG_AMT
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setRegAmt(String regAmt) {
        this.regAmt = regAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.CORP_TEL
     *
     * @return the value of registration_user.CORP_TEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getCorpTel() {
        return corpTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.CORP_TEL
     *
     * @param corpTel the value for registration_user.CORP_TEL
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setCorpTel(String corpTel) {
        this.corpTel = corpTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.BUSINESS_LICENSE
     *
     * @return the value of registration_user.BUSINESS_LICENSE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.BUSINESS_LICENSE
     *
     * @param businessLicense the value for registration_user.BUSINESS_LICENSE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.PROJ_BANK
     *
     * @return the value of registration_user.PROJ_BANK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getProjBank() {
        return projBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.PROJ_BANK
     *
     * @param projBank the value for registration_user.PROJ_BANK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setProjBank(String projBank) {
        this.projBank = projBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.GUARANTEE_ORG
     *
     * @return the value of registration_user.GUARANTEE_ORG
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getGuaranteeOrg() {
        return guaranteeOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.GUARANTEE_ORG
     *
     * @param guaranteeOrg the value for registration_user.GUARANTEE_ORG
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setGuaranteeOrg(String guaranteeOrg) {
        this.guaranteeOrg = guaranteeOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.SUPERVISORY_ORG
     *
     * @return the value of registration_user.SUPERVISORY_ORG
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getSupervisoryOrg() {
        return supervisoryOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.SUPERVISORY_ORG
     *
     * @param supervisoryOrg the value for registration_user.SUPERVISORY_ORG
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setSupervisoryOrg(String supervisoryOrg) {
        this.supervisoryOrg = supervisoryOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.USERNAME
     *
     * @return the value of registration_user.USERNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.USERNAME
     *
     * @param username the value for registration_user.USERNAME
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.USRCUSTID
     *
     * @return the value of registration_user.USRCUSTID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getUsrcustid() {
        return usrcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.USRCUSTID
     *
     * @param usrcustid the value for registration_user.USRCUSTID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setUsrcustid(String usrcustid) {
        this.usrcustid = usrcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registration_user.BUSINESS_SCOPE
     *
     * @return the value of registration_user.BUSINESS_SCOPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registration_user.BUSINESS_SCOPE
     *
     * @param businessScope the value for registration_user.BUSINESS_SCOPE
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope;
    }
}