package com.crowdfunding.pojo;

public class TDbIssue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_issue.ID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_issue.DB_VERSION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String dbVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_issue.PERSION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String persion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_issue.REMARK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_issue.ID
     *
     * @return the value of t_db_issue.ID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_issue.ID
     *
     * @param id the value for t_db_issue.ID
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_issue.DB_VERSION
     *
     * @return the value of t_db_issue.DB_VERSION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getDbVersion() {
        return dbVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_issue.DB_VERSION
     *
     * @param dbVersion the value for t_db_issue.DB_VERSION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setDbVersion(String dbVersion) {
        this.dbVersion = dbVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_issue.PERSION
     *
     * @return the value of t_db_issue.PERSION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getPersion() {
        return persion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_issue.PERSION
     *
     * @param persion the value for t_db_issue.PERSION
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setPersion(String persion) {
        this.persion = persion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_issue.REMARK
     *
     * @return the value of t_db_issue.REMARK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_issue.REMARK
     *
     * @param remark the value for t_db_issue.REMARK
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}