package com.crowdfunding.mapper;

import com.crowdfunding.pojo.CrowdTransJournal;
import com.crowdfunding.pojo.CrowdTransJournalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrowdTransJournalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(CrowdTransJournalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(CrowdTransJournalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(CrowdTransJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(CrowdTransJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<CrowdTransJournal> selectByExampleWithBLOBs(CrowdTransJournalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<CrowdTransJournal> selectByExample(CrowdTransJournalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    CrowdTransJournal selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrowdTransJournal record, @Param("example") CrowdTransJournalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CrowdTransJournal record, @Param("example") CrowdTransJournalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") CrowdTransJournal record, @Param("example") CrowdTransJournalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(CrowdTransJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CrowdTransJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_trans_journal
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(CrowdTransJournal record);
}