package com.crowdfunding.mapper;

import com.crowdfunding.pojo.CrowdVote;
import com.crowdfunding.pojo.CrowdVoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrowdVoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(CrowdVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(CrowdVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(CrowdVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(CrowdVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<CrowdVote> selectByExample(CrowdVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    CrowdVote selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrowdVote record, @Param("example") CrowdVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") CrowdVote record, @Param("example") CrowdVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(CrowdVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_vote
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(CrowdVote record);
}