package com.crowdfunding.mapper;

import com.crowdfunding.pojo.CrowdAmount;
import com.crowdfunding.pojo.CrowdAmountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrowdAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(CrowdAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(CrowdAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(CrowdAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(CrowdAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<CrowdAmount> selectByExample(CrowdAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    CrowdAmount selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrowdAmount record, @Param("example") CrowdAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") CrowdAmount record, @Param("example") CrowdAmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(CrowdAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_amount
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(CrowdAmount record);
}