package com.crowdfunding.mapper;

import com.crowdfunding.pojo.ProjInfo;
import com.crowdfunding.pojo.ProjInfoExample;
import com.crowdfunding.pojo.ProjInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    long countByExample(ProjInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByExample(ProjInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insert(ProjInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int insertSelective(ProjInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<ProjInfoWithBLOBs> selectByExampleWithBLOBs(ProjInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    List<ProjInfo> selectByExample(ProjInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    ProjInfoWithBLOBs selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProjInfoWithBLOBs record, @Param("example") ProjInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProjInfoWithBLOBs record, @Param("example") ProjInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByExample(@Param("record") ProjInfo record, @Param("example") ProjInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeySelective(ProjInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProjInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_info
     *
     * @mbg.generated Fri Sep 21 13:43:03 CST 2018
     */
    int updateByPrimaryKey(ProjInfo record);
}